#!/bin/sh
set -eu

[ "$1" = "--secret-fd" ]
[ "$2" = "3" ]
[ "$3" = "--result-fifo" ]
[ -n "$4" ]
while ! IFS= read -r secret <&3; do
  [ "$(date +%s)" -lt "$HANDOFF_DEADLINE_EPOCH" ] || exit 1
  sleep 0.05
done
[ -n "$secret" ]
secret=''
printf 'ok\n' > "$4"
